config/routes.rb
Rails.application.routes.draw do
  #devise_for :users

  root "posts#index"

  resources :posts do
    resources :comments
  end

  namespace :admin do
    resources :posts
      resources :comments
  end

  namespace :api do
    namespace :v1 do
      devise_for :users,
                 controllers: {
                   :sessions => 'api/v1/sessions',
                   :registrations => 'api/v1/registrations'
                 }
      get '/posts/:id/pdf', to: "posts#pdf"
      resources :posts do
        resources :comments
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: { in: 5..55 }
  validates :body, presence: true, length: { in: 15..255 }
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def new
    @post = Post.new
    authorize Post
  end

  # GET /posts/1/edit
  def edit
    authorize Post
  end

  def destroy
    authorize Post
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    if @post.update(post_params)
      redirect_to root_path
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      before_action :set_post, only: %i[ show edit update destroy pdf ]
      before_action :authenticate_user!

      # GET /posts or /posts.json
      def index
        @posts = Post.all.order('created_at DESC')

        render json: @posts, status: :ok
      end

      # GET /posts/1 or /posts/1.json
      def show
        post = {"post" => @post, "author" => @post.user.email}
        render json: post, status: :ok

      end

      def pdf
        pdf_html = ActionController::Base.new.render_to_string(template: 'posts/pdfzAPI.html.erb', layout: 'pdf.html', locals: { :post => @post})
        pdf = WickedPdf.new.pdf_from_string(pdf_html, header: {
          :margin => { :bottom => 10},
          content: render_to_string("posts/pdf_headerZAPI.html.erb"),

        },margin: {
          top: 20
        }, :footer => { :right => 'Page: [page] of [topage]', :margin => { :top => 10}}, encoding: "utf8", layout: "pdf",)
        send_data pdf, filename: 'file_name.pdf'
      end

      # POST /posts or /posts.json
      def create
        authorize Post
        @post = Post.new(post_params.merge(user_id: @current_user_id))

        if @post.save
          render json: { post: @post, message: "Created" }, status: :created
        else
          render json: { errors: @post.errors.full_messages.first, message: "Not created" }, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /posts/1 or /posts/1.json
      def update
        authorize Post
        if @post.update(post_params)
          render json: { post: @post, message: "Updated successfully" }, status: :created
        else
          render json: { errors: @post.errors.full_messages.first, message: "Not created" }, status: :unprocessable_entity
        end
      end

      # DELETE /posts/1 or /posts/1.json
      def destroy
        authorize Post
        @post.destroy

        render json: { message: "Post destroyed successfully" }, status: :ok

      end

      private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def post_params
        params.require(:post).permit(:title, :body)
      end
    end

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "post.pdf",
               template: "posts/pdf.html.erb",
               header: {
                 :margin => { :bottom => 10},
                 html: {
                   template: "posts/pdf_header.html.erb"
                 }
               },
               encoding: "utf8",
               layout: "pdf",
               margin: {
                 top: 20
               },
               :footer => { :right => 'Page: [page] of [topage]', :margin => { :top => 10}}
      end
    end
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    authorize Post
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation text-danger">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control", placeholder: "Post title..."  %>
  </div>

  <div class="field form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control", placeholder: "Post body..." %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
    <%= link_to posts_path do %>
      <button class="btn btn-secondary">Back</button>
    <% end %>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<div class="container my-3">
  <% @posts.each do |post| %>
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <p><%= post.title %></p>
        <p class="font-italic">by <%= post.user.email %></p>
      </div>
      <div class="card-body">
        <p class="card-text"><%= post.body %></p>
        <%= link_to 'Show', post_path(post), class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_admin_post_path(post), class: "btn btn-primary" %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>
</div>


app/views/posts/edit.html.erb
<h2 class="mt-4 text-center">Editing Post</h2>

<%= render 'form', post: @post %>

<div class="mt-2">
  <%= link_to 'Show', @post, class: "btn btn-primary" %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <%= render "posts/posts" %>

  <div class="container text-center mt-2 w-75">
    <%= link_to 'New Post', new_admin_post_path, class: "py-3 w-100 btn btn-primary" %>
  </div>
</div>

app/views/posts/new.html.erb
<h2 class="mt-4 text-center">Add New Post</h2>

<%= render 'form', post: @post %>

app/views/posts/pdf.html.erb
<div class="container">
  <div class="title-wrapper" style="">
    <h2 class="title mt-2"><%= @post.title %></h2>
  </div>
  <p class="subtitle post"><%= @post.body %></p>
  <div class="hero my-3 comments-wrapper">
    <h4>Comments</h4>
    <%= render "comments/comment_pdf", collection: @post %>
  </div>
</div>

app/views/posts/pdfZAPI.html.erb
<div class="container">
  <div class="title-wrapper" style="">
    <h2 class="title mt-2"><%= post.title %></h2>
  </div>
  <p class="subtitle post"><%= post.body %></p>
  <div class="hero my-3 comments-wrapper">
    <h4>Comments</h4>
    <%= render "comments/comment_pdfZAPI", comments: post.comments %>
  </div>
</div>

app/views/posts/pdf_header.html.erb
<header>
  <p>Title: <%= @post.title %> | Created: <%= @post.created_at.to_date %> | Author: <%= @post.user.email %></p>
</header>

app/views/posts/pdf_headerZAPI.html.erb
<header>
<!--  <p>Title: <%#= post.title %> | Created: <%#= post.created_at.to_date %> | Author: <%#= post.user.email %></p>-->
  <p>Test</p>
</header>

app/views/posts/show.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <h2 class="title mt-2"><%= @post.title %></h2>
    <p class="font-italic">by <%= @post.user.email %></p>
  </div>
  <hr>
  <p class="subtitle"><%= @post.body %></p>
  <hr>
  <div class="hero my-3">
    <h4>Comments</h4>
    <%= render "comments/comment", collection: @post %>
  </div>
  <hr>
  <div class="hero my-3">
    <h4>Add a comment</h4>
    <%= render "comments/form" %>
  </div>

  <%= link_to 'Edit', edit_admin_post_path(@post), class: "btn btn-primary" %>
  <%= link_to 'Back', posts_path, class: "btn btn-secondary" %>
  <%= link_to "Generate PDF", post_path(@post, :format => :pdf) %>
</div>